### ISSUE TITLE
$PID_ROOT on Raspberry Pi is not created if missing while doing an upgrade

### ISSUE THREAD

**Issue by SourceCodeSourcerer** [NetHome/NetHomeServer#10]
#### Assumptions
New installation of NetHomeServer
Bug: Previously, the /var/run/nethome directory was not created during install.
#### Bug
Upgrade NetHomeServer from nightly build
Bug: **The /var/run/nethome directory was not checked for existence while performing an upgrade**
Suggested fix is to let **upgrade.sh** make this check, add to line 26 onwards:
```
# Verify $PID_ROOT exists (a previous bug!)
if [ ! -d $PID_ROOT ]; then
  echo "Creating missing '$PID_ROOT' directory"
  mkdir -p $PID_ROOT  
fi
```
#### Explanation
The check for the running process fails and causes the upgrade to take a long time while killing and restarting the server.

I will make a pull request for this.

**Comment by stefangs** [comment]
Thanks for report with fix! Merged and released in nightly build
