### ISSUE TITLE
Unable to set HouseCode value larger than H

### ISSUE THREAD

**Issue by robbanl** [NetHome/NetHomeServer#19]
Hi,

I'm awaiting approval for the forum but I'll post a bug report here for now.

**Environment**: I'm using a Tellstick Duo on a Raspberry Pi 2. Tellstick is powered by an external USB hub with separate power. Using latest Jessie as OS for rPi and also using the nighly build of OHS.

**The problem**: Adding a Nexa remote power switch works fine for a while. Then it stops working. Manual remote (the one received with the power switch) works all the time, and also works fine from where the Tellstick is placed.

I removed all items and began blank. Added the remote power switch and noted that is said _HouseCode_ O and _Button_ 8. Tried on/off/toggle and it worked just fine. Then I restarted the daemon using _sudo nethome restart_ command and then the switch was not working. When I looked at the settings of the lamp, it had changed to _HouseCode_ A and _Button_ 8. I was not able to manually save the changes to have the _HouseCode_ set correctly.

Tried to edit the file _/etc/opt/nethome/config.xml_ manually to set the correct values and restarted the daemon. The value is still unchanged on site, but correct in XML.

Noticed  that I had Swedish characters in the names that might mess with the XML, so tried removing those. Saved and restarted. Names were updated but the site still showed incorrect _HouseCode_.

**Comment by robbanl** [comment]
Do I understand the code at https://github.com/NetHome/NetHomeServer/blob/master/home-items/rf-items/src/main/java/nu/nethome/home/items/nexa/NexaLamp.java#L136 correctly, that the biggest character a HouseCode can have is H?

**Comment by robbanl** [comment]
Manual testing confirms that H is the highest letter that's allowed. Is there a reason for this or can I create a PR with a bump of "highest" letter allowed?

**Comment by stefangs** [comment]
Thanks for the report Robbanl. You were correct in that the code stopped codes higher than H, even though the protocol supports up to P. This is now fixed, and I also fixed so it supports entering lower case characters. The fix is in the nightly build now.

**Comment by robbanl** [comment]
Thank you very much @stefangs ! I just updated and everything works great now :)
