### ISSUE TITLE
Changes to Whitelist username creation

### ISSUE THREAD

**Issue by SteveyO** [NetHome/NetHomeServer#2]
Hi NetHome,

I work for Philips Hue Developer Support.  In case you were not aware, in a few months time we will be changing the way usernames are created on the bridge (for security reasons).  Custom whitelist usernames will no longer be allowed and the bridge randomly generated username must be used instead.  Please see below link for more information:
http://www.developers.meethue.com/documentation/important-whitelist-changes

I checked your code and in PhilipsHueBridge.java line 185 (RegisterUser method) you are setting the username.  After February 2016 this code won't work so the passing of the user as a parameter and the setting of the "username" in the POST body should be removed here.  The randomly generated bridge username is returned in the bridge success response,  however it looks like you have this code in place already so hopefully the changes should be minimal for you.   Apologies for the inconvenience.

Thanks
Steve

**Comment by stefangs** [comment]
Committed a change according to your information and have released it in the nightly build. The username is now a read only field in the Home Item that is updated when you register the item. Documentation Wiki is also updated.

I must say I am really amazed by the excellent level of the Philips Hue support towards people who integrate with them. This level of detailed help is far beyond what I would expect - really good work!

**Comment by SteveyO** [comment]
Hi Stefan,
Thanks for the really nice comment, appreciated.
And thanks for making the change so quickly.  I just checked your commit changes and this looks perfect, although I haven't tested of course.  Good stuff! 
Steve
